// AtlComDll.idl : IDL source for AtlComDll
//

// This file will be processed by the MIDL tool to
// produce the type library (AtlComDll.tlb) and marshalling code.
import "oaidl.idl";
import "ocidl.idl";

[
  object,
  uuid(D427CA52-AF28-40a4-A5C2-97EA029DCD0F),
  pointer_default(unique)
]
interface IKnowledgeBase : IUnknown
{
  HRESULT Answer([out] BYTE* pbResult);
};

[
  uuid(CEF16732-BF43-4FEE-A362-5C2FFE216E8E),
  version(1.0),
]
library AtlComDllLib
{
  importlib("stdole2.tlb");

  [
    uuid(3FAF4A44-3542-401C-9EF9-58EF90FBFCD8)
  ]
  coclass Component1
  {
    [default] interface IKnowledgeBase;
  };
};

